### ISSUE TITLE
Only works with Python >= 3.7

### ISSUE THREAD

**Issue by sadreck** [frostming/flask-crontab#1]
Hi,

Kudos for this package, it's exactly what I was looking for.

The documentation says that it works on Python 3.5+ however it's invoking subprocess.run using the `text` and `capture_output` parameters which have been introduced in 3.7.

https://github.com/frostming/flask-crontab/blob/master/flask_crontab.py#L137 and https://github.com/frostming/flask-crontab/blob/master/flask_crontab.py#L158

And below is the output when running on Python 3.6:

```
TypeError: __init__() got an unexpected keyword argument 'capture_output'
TypeError: __init__() got an unexpected keyword argument 'text'
```

**Comment by frostming** [comment]
Oh, that was missed since subprocess calls have been mocked in the CI.

Thanks for the report.
